templates/lego_certificate_renew.sh.j2: for each variable in variables_to_check_for_being_set, add a stanza to check if the variable is set

diff --git a/templates/lego_certificate_renew.sh.j2 b/templates/lego_certificate_renew.sh.j2
--- a/templates/lego_certificate_renew.sh.j2
+++ b/templates/lego_certificate_renew.sh.j2
@@ -8,6 +8,15 @@ source /etc/default/lego
 source /etc/lego/config
 set +o allexport
 
+{% if variables_to_check_for_being_set is defined %}
+{% for variable_to_check in variables_to_check_for_being_set %}
+[[ -z "${{ '{' }}{{ variable_to_check }}{{ '}' }}" ]] && {
+    echo "Error, {{variable_to_check}} is unset..."
+    exit 3
+}
+{% endfor%}
+{% endif%}
+
 [ -z "$EMAIL" ] && {
         echo "EMAIL is not set..."
         exit 1
